# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Copy all source code
COPY . .

# Upgrade pip and install the package
RUN pip install --upgrade pip \
    && pip install .

# Expose the MCP server port
EXPOSE 13000

# Default command to start the MCP server
CMD ["agentmode"]
